### ISSUE TITLE
Possible to use this with VuePress?

### ISSUE THREAD

**Issue by brandonkelly** [MatteoGabriele/vue-analytics#120]
I’m attempting to use vue-analytics in a [VuePress](https://vuepress.vuejs.org/) site, but getting the following error when building the docs:

```
Rendering page: /Error rendering /:
ReferenceError: window is not defined
    at S (.../node_modules/vue-analytics/dist/vue-analytics.js:1:5111)
    at Function.Vue.use (.../node_modules/vue/dist/vue.runtime.common.js:4751:14)
    at enhanceApp (docs/.vuepress/enhanceApp.js:4:8)
    at createApp (node_modules/vuepress/lib/app/app.js:81:2)
    at module.exports.__webpack_exports__.default (node_modules/vuepress/lib/app/serverEntry.js:4:26)
    at new Promise (<anonymous>)
    at module.exports.__webpack_exports__.default (node_modules/vuepress/lib/app/serverEntry.js:3:26)
    at .../node_modules/vue-server-renderer/build.js:8426:15
    at new Promise (<anonymous>)
    at .../node_modules/vue-server-renderer/build.js:8388:14
    at Object.renderToString (.../node_modules/vue-server-renderer/build.js:8564:9)
    at renderPage (.../node_modules/vuepress/lib/build.js:143:29)
    at build (.../node_modules/vuepress/lib/build.js:66:11)
    at <anonymous>
```

So looks like SSR support is not fully there. I think VuePress is a pretty typical Vue app.

**Comment by MatteoGabriele** [comment]
Hi @brandonkelly 
thanks for your feedback! I'm going to have a look and see if I can make it SSR friendly :)

**Comment by brandonkelly** [comment]
Thanks for taking a stab at it! I’m still getting an error:

```
ReferenceError: window is not defined
    at S (.../vp-analytics-test/node_modules/vue-analytics/dist/vue-analytics.js:1:5173)
    at Function.Vue.use (.../vp-analytics-test/node_modules/vue/dist/vue.runtime.common.js:4751:14)
    at enhanceApp (docs/.vuepress/enhanceApp.js:4:8)
    at createApp (node_modules/vuepress/lib/app/app.js:81:2)
    at module.exports.__webpack_exports__.default (node_modules/vuepress/lib/app/serverEntry.js:4:26)
    at new Promise (<anonymous>)
    at module.exports.__webpack_exports__.default (node_modules/vuepress/lib/app/serverEntry.js:3:26)
    at .../vp-analytics-test/node_modules/vue-server-renderer/build.js:8426:15
    at new Promise (<anonymous>)
    at .../vp-analytics-test/node_modules/vue-server-renderer/build.js:8388:14
    at Object.renderToString (.../vp-analytics-test/node_modules/vue-server-renderer/build.js:8564:9)
    at renderPage (.../vp-analytics-test/node_modules/vuepress/lib/build.js:143:29)
    at build (.../vp-analytics-test/node_modules/vuepress/lib/build.js:66:11)
    at <anonymous>
```

Here’s a sample project: https://github.com/brandonkelly/vp-analytics-test

**Comment by MatteoGabriele** [comment]
I've made couple more changes and now I can build the application.
Update to v 5.10.6

thanks for your time, helped a lot :)

**Comment by brandonkelly** [comment]
Thanks! It is in fact able to build now. I’ve [added it](https://github.com/craftcms/docs/commit/3efae485850c27e98ecf438ec5ddc3657982fb52) to one of our documentation projects, but it doesn’t appear to actually be sending anything to GA. Were you able to test whether it was actually working on your end in that test project?

**Comment by MatteoGabriele** [comment]
@brandonkelly yes was sending events, even if in the repo you made the domain ID was fake.
when you set the `debug.enabled` to true, you can check all events that are sent to Google Analytics: that's the proof that is working.
